# https://github.com/fongandrew/hydeout/blob/gh-pages/_config.yml

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Amod
tagline:          'A little experiment'
description:      'Based on the <a href="http://jekyllrb.com" target="_blank">Jekyll</a> static website framework.'
url:              https://cath7.github.io/test-website
baseurl:          '/test-website'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Master of Things'
  url:            https://cath7.github.io/test-website

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

#theme: minima
#theme: jekyll-theme-hydeout
remote_theme: cath7/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink: /:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
